name: main

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: say hi
        run: |
          echo "Time for random sleep"
          sleep $(shuf -i 5-20 -n 1)
    
      # - name: wait for older workflows to conclude
      #   uses: ./.github/actions/wait-for-workflow
      #   with:
      #     branch: main
      #     delay: 15
      #     cancel-on-newer-workflow: true
