name: main

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: say hi
        run: |
          echo "hello world"
    
      - name: Test wait for deploys
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.runId);
            const { owner, repo } = context.repo;
            const cancelOptions = {
              owner,
              repo,
              run_id: context.runId,
            };

            await github.rest.actions.cancelWorkflowRun(cancelOptions);

      # - name: cancel via cli
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     IN_PROGRESS=($(gh api \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       /repos/${{ github.repository }}/actions/workflows/main.yml/runs\?=main&status=in_progress \
      #       | jq -r '.workflow_runs[].id))

      #     QUEUED=($(gh api \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       /repos/${{ github.repository }}/actions/workflows/main.yml/runs\?=main&status=queued \
      #       | jq -r '.workflow_runs[].id))

      #     if []
      #     then
      #       echo "Canceling self"
      #       gh run cancel ${{ github.run_id	}} --repo ${{ github.repository }}
      #     fi

      - name: stall 1
        run: |
          sleep 5
    
      - name: stall 2
        run: |
          sleep 5
