name: main

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: |
          echo "hello world"
    
      - name: Test wait for deploys
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
