name: main

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: say hi
        run: |
          echo "hello world"
    
      - name: Test wait for deploys
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            const input = {
              branch: 'main',
              delay: 2,
              cancelOnNewerWorkflow: true,
            }
            const wait = require('./.github/workflows/wait.ts');
            await wait(github, context, input);

      - name: cancel via cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_IDS=($(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/workflows/main.yml/runs \
            | jq -r '.workflow_runs[] | select(.status == "in_progress" or .status == "pending").id'))
          for id in "${RUN_IDS[@]}"; do
            echo "Canceling release worflow run $id"
            gh run cancel $id --repo ${{ github.repository }}
          done

      - name: stall
        run: |
          sleep 20
