name: main

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: say hi
        run: |
          echo "hello world"
    
      - name: Test wait for deploys
        uses: actions/github-script@v6
        with:
          script: |
            const input = {
              branch: 'main',
              delay: 2,
              cancelOnNewerWorkflow: true,
            }
            const wait = require('${{ github.action_path }}/wait.ts');
            await wait(github, context, input);
